services:
  frontend:
    build:
      context: .
      target: development-stage
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - API_HOST=app
    networks:
      - vendas-network
    command: npm run dev

networks:
  vendas-network:
    external: true
    name: vendas-network