version: '3.8'

services:
  frontend:
    build:
      context: .
      target: ${BUILD_TARGET:-production-stage}
    profiles: ["development", "production"]  # Adicione ambos os perfis
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - VITE_API_BACKEND_HOST=${API_HOST:-backend}
      - VITE_API_BACKEND_PORT=${API_PORT:-8000}
    networks:
      - vendas-network

networks:
  vendas-network:
    external: true