services:
  frontend:
    build:
      context: .
      target: development-stage
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api
    networks:
      - vendas-network
    command: npm run dev

networks:
  vendas-network:
    external: true
    name: vendas-network